### ISSUE TITLE
Can't boot into the iso file

### ISSUE THREAD

**Issue by WoffleTbh** [Deltara3/amogus#23]
![uwu](https://user-images.githubusercontent.com/79484501/137701508-eba95b25-483d-4f4c-8695-756348dffdec.png)

**Comment by unkn0wncvm1** [comment]
[Qemu For Windows](https://www.qemu.org/download/#windows)

**Comment by GrpeApple** [comment]
Lamogus

**Comment by unkn0wncvm1** [comment]
`⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛
⬛⬛🔴🔴🔴🔴⬛🔴⬛⬛🔴⬛🔴🔴🔴🔴⬛⬛
⬛⬛🔴⬛⬛⬛⬛🔴⬛⬛🔴⬛🔴⬛⬛⬛⬛⬛
⬛⬛🔴🔴🔴🔴⬛🔴⬛⬛🔴⬛🔴🔴🔴🔴⬛⬛
⬛⬛⬛⬛⬛🔴⬛🔴⬛⬛🔴⬛⬛⬛⬛🔴⬛⬛
⬛⬛🔴🔴🔴🔴⬛⬛🔴🔴⬛⬛🔴🔴🔴🔴⬛⬛
⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛`

**Comment by Commensalism1997** [comment]
ඞ amogus

**Comment by Deltara3** [comment]
QEMU was confirmed to work when it was first tested.
