### ISSUE TITLE
where shitlang 😭 

### ISSUE THREAD

**Issue by sertdfyguhi** [Deltara3/amogus#53]
Where Shitlang I Don't See It Where Is It

**Comment by Deltara3** [comment]
That was added a while ago.

File [here](https://github.com/Deltara3/amogus/blob/main/lang/ඞ.shit).

**Comment by sertdfyguhi** [comment]
damn.... but where the fuck is it in the lang.md 😭

**Comment by sertdfyguhi** [comment]
nevermind im just stupid as fuck lmao
