### ISSUE TITLE
What to do with duplicate file extensions?

### ISSUE THREAD

**Issue by Dogey11** [Deltara3/amogus#65]
I was going to open a PR to add [Beef](https://www.beeflang.org/) which uses the file extension `.bf`, however this is also one of the 2 extensions used by brainfuck which are `.bf` and `.b`, Which wouldn't be an issue but there is already a file named `ඞ.b` for B, so just renaming the brainfuck file wouldn't work.

The only solution I could think of is sorting the files in folders by language but that could be tedious

**Comment by Deltara3** [comment]
Ah that's something I've thought about but haven't found an answer to yet. It would be tedious and slightly meaningless to create a folder for each one, as only one file for each language is in the lang folder.

We could change the naming scheme maybe to something like `ඞ.langname.langext`. This could still be quite time consuming, but would preserve the main folder.

Let me know what you think!

**Comment by Dogey11** [comment]
> ```
> lang
> └── csharp
>     ├── joke
>     │   ├── ඞ_420.cs
>     │   └── ඞ_69.cs
>     └── ඞ.cs
> ```

This way would be the best choice imo, the other method would get messy.


 files like ` ඞ.iso` and ` ඞ.png` could be put into a `misc` folder as well.

**Comment by Deltara3** [comment]
Reas0nable, I shall rearrange everything.

**Comment by S4ltster** [comment]
> Reasonable, I shall rearrange everything.

**Unlucky**

**Comment by Deltara3** [comment]
The lang folder has been rearranged, so you may submit your pr when its ready.

**Comment by Dogey11** [comment]
> The lang folder has been rearranged, so you may submit your pr when its ready.

submitted: #66
